import type { Metadata } from 'next'
import Link from 'next/link'
import { getLocale } from 'next-intl/server'
import { FriendLinkApplicationForm } from '@/components/FriendLinkApplicationForm'
import { FriendLinkSiteKit } from '@/components/FriendLinkSiteKit'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.new-universe.cn'
export async function generateMetadata(): Promise<Metadata> { const locale = await getLocale(); const zh = locale === 'zh'; return { title: zh ? '申请友链 - 墨千' : 'Apply for a friend link - Byte & Beyond', description: zh ? '提交你的站点资料，申请与墨千交换友链。' : 'Submit your site profile to exchange links with Byte & Beyond.', alternates: { canonical: `${SITE_URL}/${locale}/links/apply` }, robots: { index: false, follow: true } } }
export default async function FriendLinkApplyPage() { const locale = await getLocale(); const zh = locale === 'zh'; const steps = zh ? ['先在你的网站添加本站链接', '复制下方资料，一键完成添加', '提交资料，进入人工审核', '通过后展示并开始互链守护'] : ['Add our link to your site first', 'Copy the link kit below', 'Submit your profile for human review', 'Appear on the page after approval']; return <main className="relative min-h-screen overflow-hidden bg-[#f8fafc] px-6 py-16 dark:bg-slate-950 md:px-12 lg:px-24"><div className="pointer-events-none absolute inset-0 opacity-60 [background-image:radial-gradient(#cbd5e1_1px,transparent_1px)] [background-size:24px_24px] dark:opacity-15" /><div className="relative mx-auto max-w-5xl"><Link href={`/${locale}/links`} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-blue-600">← {zh ? '返回友链页' : 'Back to friends'}</Link><div className="mt-14 grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><section className="self-start lg:sticky lg:top-28"><p className="text-xs font-bold uppercase tracking-[.24em] text-blue-600">Link exchange / 2026</p><h1 className="mt-5 text-4xl font-black tracking-tight text-slate-950 dark:text-white md:text-6xl">{zh ? <>好内容，<br /><span className="bg-gradient-to-r from-blue-600 to-violet-600 bg-clip-text text-transparent">彼此抵达。</span></> : <>Good work,<br /><span className="bg-gradient-to-r from-blue-600 to-violet-600 bg-clip-text text-transparent">mutually found.</span></>}</h1><p className="mt-6 max-w-md text-base leading-8 text-slate-500">{zh ? '这里收录长期创作、真诚表达的独立站点。完善的资料会让读者更快理解你的内容，也让你的友链卡片更有质感。' : 'A home for independent sites that publish with care. A richer profile helps readers understand your work at a glance.'}</p><div className="mt-10 space-y-4">{steps.map((item, index) => <div key={item} className="flex items-center gap-3 text-sm font-medium text-slate-600 dark:text-slate-300"><span className="flex h-7 w-7 items-center justify-center rounded-full border border-blue-200 bg-blue-50 text-xs font-bold text-blue-600 dark:border-blue-800 dark:bg-blue-950">0{index + 1}</span>{item}</div>)}</div><FriendLinkSiteKit locale={locale} /></section><FriendLinkApplicationForm locale={locale} /></div></div></main> }
