
import { Post } from './types';

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    title: 'The Future of Neural Interfaces',
    excerpt: 'How brain-computer connections are evolving from science fiction to everyday medical reality.',
    content: `The intersection of biology and silicon is no longer limited to the realms of speculative fiction. Recent breakthroughs in neural lace technology and micro-electrode arrays are paving the way for a future where high-bandwidth communication between the human brain and external computing systems is not just possible, but seamless.\n\n### The Rise of Non-Invasive Systems\nWhile companies like Neuralink focus on surgical implants, a new wave of startups is exploring high-fidelity EEG and fNIRS caps that can read intent without a single incision. These systems are being used to restore mobility to stroke patients and provide new avenues for creative expression in digital environments.\n\n### Ethics and Sovereignty\nAs we integrate deeper with AI-driven interfaces, the question of cognitive liberty becomes paramount. Who owns the data generated by your thoughts? How do we prevent neural manipulation? These are the challenges of the next decade.`,
    author: 'Elena Vance',
    date: 'Oct 12, 2024',
    readTime: '6 min read',
    category: 'Neuroscience',
    imageUrl: 'https://picsum.photos/seed/neuro/1200/600',
    tags: ['Tech', 'Future', 'Medical']
  },
  {
    id: '2',
    title: 'Minimalism in the Age of Spatial Computing',
    excerpt: 'Redefining user interface design as we transition from flat screens to immersive 3D environments.',
    content: `Spatial computing demands a radical rethink of visual hierarchy. When the world is your canvas, traditional buttons and menus feel restrictive. We are moving towards "intent-based" design, where the system anticipates needs based on gaze and subtle gestures.\n\n### The Invisible UI\nThe best interface is the one you don't see. In AR and VR, we leverage depth, lighting, and sound to guide users. This is the ultimate expression of minimalism—where the technology disappears, leaving only the experience.\n\n### Apple Vision Pro and the Paradigm Shift\nWith the introduction of new spatial platforms, designers must learn to think in volumes rather than planes. Shadows are no longer just aesthetic; they are functional cues for interaction.`,
    author: 'Marcus Aurelius',
    date: 'Sep 28, 2024',
    readTime: '8 min read',
    category: 'Design',
    imageUrl: 'https://picsum.photos/seed/spatial/1200/600',
    tags: ['UX', 'AR/VR', 'Apple']
  },
  {
    id: '3',
    title: 'Sustainable Energy: The Solid-State Revolution',
    excerpt: 'Why solid-state batteries are the missing link for a completely green transportation infrastructure.',
    content: `Lithium-ion has served us well, but it has reached its physical limits. Solid-state batteries promise higher energy density, faster charging times, and most importantly, improved safety.\n\n### Breaking the 1000km Barrier\nMajor automotive manufacturers are racing to commercialize cells that could give EVs a range exceeding 1000km on a single 10-minute charge. This would effectively eliminate range anxiety and make internal combustion engines obsolete for good.\n\n### Scaling the Manufacturing\nThe hurdle remains cost and manufacturing complexity. Current techniques are difficult to scale to the millions of units required annually, but pilot lines are already showing promising yields.`,
    author: 'Sarah Chen',
    date: 'Aug 15, 2024',
    readTime: '5 min read',
    category: 'Sustainability',
    imageUrl: 'https://picsum.photos/seed/energy/1200/600',
    tags: ['Energy', 'Climate', 'Innovation']
  }
];
